---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-nfs
  labels:
    pv-name: prometheus-nfs
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 10.86.1.244
    path: /var/nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-class: ssd
    volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/nfs
  labels:
    app: prometheus
    prometheus: prometheus-k8s
  name: prometheus-prometheus-k8s-db-prometheus-prometheus-k8s-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  volumeName: prometheus-nfs
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 40Gi
  phase: Bound
---
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: prometheus-nfs
provisioner: kubernetes.io/nfs


