kind: Pod
apiVersion: v1
metadata:
  name: test-pod
  #  namespace: kube-system
spec:
  containers:
  - name: test-pod
    image: gcr.io/google_containers/busybox:1.24
    command:
      - "/bin/sh"
    args:
      - "-c"
      - "touch /mnt/NFS-SUCCESS && exit 0 || exit 1"
    volumeMounts:
      - name: vnfs
        mountPath: /mnt
  restartPolicy: "Never"
  volumes:
    - name: vnfs
      persistentVolumeClaim:
        claimName: prometheus-prometheus-k8s-db-prometheus-prometheus-k8s-0
