# Configure admin password
adminPassword: admin

service:
 type: NodePort

# Ingress configuration
#ingress:
#  enabled: true
#  annotations:
#    kubernetes.io/ingress.class: nginx
#  hosts:
#    - grafana.example.com
#  tls:
#    - hosts:
#      - grafana.example.com
#      secretName: monitoring-tls

# Configure persistent storage
persistence:
 enabled: true
 accessModes:
   - ReadWriteOnce
 ## Use a StorageClass
 storageClassName: example-nfs
 ## Create a PersistentVolumeClaim of 10Gi
 size: 8Gi
 ## Use an existing PersistentVolumeClaim (my-pvc)
 #existingClaim: my-pvc

# Enable sidecar for provisioning
sidecar:
 datasources:
   enabled: true
   label: grafana_datasource
 dashboards:
   enabled: true
   label: grafana_dashboard
