# Alertmanager configuration
alertmanager:
 enabled: true
 service:
   type: NodePort
 # ingress:
 #  enabled: true
 #  hosts:
 #  -  prometheus-alertmanager.example.com
 #  annotations:
 #    kubernetes.io/ingress.class: nginx
 #    nginx.ingress.kubernetes.io/auth-type: basic
 #    nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
 #    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
 #  tls:
 #    - hosts:
 #      - prometheus-alertmanager.example.com
 #      secretName: monitoring-tls
 persistentVolume:
   enabled: true
   ## Use a StorageClass
   storageClass: nfs-sc
   ## Create a PersistentVolumeClaim of 2Gi
   size: 2Gi
   ## Use an existing PersistentVolumeClaim (my-pvc)
   #existingClaim: my-pvc

# Create a specific service account
serviceAccounts:
 nodeExporter:
   name: prometheus-node-exporter

# Allow scheduling of node-exporter on master nodes
nodeExporter:
 hostNetwork: false
 hostPID: false
 podSecurityPolicy:
   enabled: true
   annotations:
     apparmor.security.beta.kubernetes.io/allowedProfileNames: runtime/default
     apparmor.security.beta.kubernetes.io/defaultProfileName: runtime/default
     seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
     seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
 tolerations:
   - key: node-role.kubernetes.io/master
     operator: Exists
     effect: NoSchedule

# Disable Pushgateway
pushgateway:
 enabled: false

 # Prometheus configuration
server:
 service:
   type: NodePort
# ingress:
#   enabled: true
#   hosts:
#   - prometheus.example.com
#   annotations:
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/auth-type: basic
#     nginx.ingress.kubernetes.io/auth-secret: prometheus-basic-auth
#     nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
#   tls:
#     - hosts:
#       - prometheus.example.com
#       secretName: monitoring-tls
 persistentVolume:
   enabled: true
   ## Use a StorageClass
   storageClass: nfs-sc
   ## Create a PersistentVolumeClaim of 8Gi
   size: 8Gi
   ## Use an existing PersistentVolumeClaim (my-pvc)
   #existingClaim: my-pvc
